Fix for GCC 4.2.1 on X86 target
GCC 4.2.1 fails with the error:

external/chromium/net/base/gzip_header.cc: In member function
'GZipHeader::Status GZipHeader::ReadMore(const char*, int, const
char**)':
external/chromium/net/base/gzip_header.cc:108: error: no matching
function for call to 'min(ptrdiff_t, int)'

Cast the second int argument to ptrdiff_t so it doesn't complain.

Change-Id: I1bcb4476d7ff92aa00d41aa42118a72351373a46